[project]
name = "bloggr"
version = "1.0.0"
description = "A production-level flask blog web application."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"